{
  "about_info":[
    "2015年毕业于北京理工大学珠海学院，专业计算机科学与技术",
    "由于个人原因，毕业后没从事回计算机行业",
    "I lack of work experience,but I will use the rest time to learn the technology",
    "I need a chance"
  ],
  "skill_info":"前端的学习需要持之以恒，知识深度与广度都很重要。而前端开发的重中之重就是原生javascript的理解，而如今的思路必需有模块化，组件化，工程化",
  "angularJs":[
    "熟练运用angularJS处理移动端的模块开发",
    "模块组件化",
    "了解双绑的背后实现",
    "熟练的指令编写"
  ],
  "html":[
    "理解Web标准",
    "熟练运用html标签",
    "掌握xml及xhtml标记语言",
    "掌握html5如SVG新特性及一些新的API"
  ],
  "css":[
    "熟练运用css及css3新属性",
    "注重浏览器兼容性",
    "掌握bootstrap框架及一些源码的实现",
    "了解css预编译器Less"
  ],
  "javaScript":[
    "掌握jQuery",
    "掌握原生JS的编程",
    "正在关注JavaScript性能优化问题"
  ],
  "exp_info":"web前端自学路上颠颠簸簸。",
  "contact_info":[
    "学习是一个充实愉悦的过程",
    "我并不是一个有天赋的前端入门者，但是我有持续学习的耐心和对前端工作的热情",
    "希望我的简历能让您看到",
    "希望我的前端工作经历能从这一刻开始"
  ]
}